KeKhaiTaiSanThuNhap/Models/DM_ChucVu_ChucDanh.cs
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KeKhaiTaiSanThuNhap.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class DM_ChucVu_ChucDanh
    {
        public int Ma_ChucVu_ChucDanh { get; set; }
        public string Ten_ChucVu_ChucDanh { get; set; }
    }
}

KeKhaiTaiSanThuNhap/Controllers/DM_ChucVu_ChucDanhController.cs
using System;
using System.Collections.Generic;
using System.Configuration;
using System.Data;
using System.Data.Entity;
using System.Data.SqlClient;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using KeKhaiTaiSanThuNhap.Models;

namespace KeKhaiTaiSanThuNhap.Controllers
{
    [Authorize(Roles = "ADMIN")]
    public class DM_ChucVu_ChucDanhController : Controller
    {
        private KSTNEntities db = new KSTNEntities();
        private UserInfo user = new UserInfo();
        public JsonResult GetChucVu()
        {
            var data = db.DM_ChucVu_ChucDanh.Select(_ => new { MaChucVu = _.Ma_ChucVu_ChucDanh, TenChucVu = _.Ten_ChucVu_ChucDanh });
            return Json(data, JsonRequestBehavior.AllowGet);
        }

        // GET: DM_ChucVu_ChucDanh
        public ActionResult Index()
        {
            if (user.CheckQuyen("DM_ChucVu", "Xem"))
            {
                return new HttpStatusCodeResult(404, "Not found");
            }
            return View();
        }

        [HttpPost]
        public JsonResult Create([Bind(Include = "Ma_ChucVu_ChucDanh,Ten_ChucVu_ChucDanh")] DM_ChucVu_ChucDanh dM_ChucVu_ChucDanh)
        {
            db.DM_ChucVu_ChucDanh.Add(dM_ChucVu_ChucDanh);
            
            db.SaveChanges();
            return Json(dM_ChucVu_ChucDanh, JsonRequestBehavior.AllowGet);
        }

     
        public JsonResult LoadData()
        {
            var draw = Request.Form.GetValues("draw").FirstOrDefault();
            var start = Request.Form.GetValues("start").FirstOrDefault();
            var length = Request.Form.GetValues("length").FirstOrDefault();
           
            var Ten_ChucVu_ChucDanh = Request.Form.GetValues("columns[1][search][value]").FirstOrDefault();
            int pageSize = length != null ? Convert.ToInt32(length) : 0;
            int skip = start != null ? Convert.ToInt32(start) : 0;
            int recordsTotal = 0;

            var data = (from cv in db.DM_ChucVu_ChucDanh
                        
                        select new { cv.Ma_ChucVu_ChucDanh, cv.Ten_ChucVu_ChucDanh }).ToList();

            try
            {
                var ordercolumn = Request.Form.GetValues("order[0][column]").FirstOrDefault();
                var sortColumn = Request.Form.GetValues("columns[" + ordercolumn + "][data]").FirstOrDefault();
                var sortColumnDir = Request.Form.GetValues("order[0][dir]").FirstOrDefault();

                if (!string.IsNullOrEmpty(Ten_ChucVu_ChucDanh))
                {
                    data = data.Where(a => a.Ten_ChucVu_ChucDanh.ToUpper().Contains(Ten_ChucVu_ChucDanh.ToUpper())).ToList();
                }

                if (sortColumnDir == "asc")
                {
                    if (sortColumn == "Ten_ChucVu_ChucDanh")
                    {
                        data = data.OrderBy(_ => _.Ten_ChucVu_ChucDanh).ToList();
                    }
                }
                else
                {
                    if (sortColumn == "Ten_ChucVu_ChucDanh")
                    {
                        data = data.OrderByDescending(_ => _.Ten_ChucVu_ChucDanh).ToList();
                    }

                }
            }
            catch { }

            
            recordsTotal = data.Count();
            var data1 = data.Skip(skip).Take(pageSize).ToList();
            return Json(new { draw = draw, recordsFiltered = recordsTotal, recordsTotal = recordsTotal, data = data1 }, JsonRequestBehavior.AllowGet);
        }

        [HttpPost]
        public ActionResult Edit([Bind(Include = "Ma_ChucVu_ChucDanh,Ten_ChucVu_ChucDanh")] DM_ChucVu_ChucDanh dM_ChucVu_ChucDanh)
        {
            if (user.CheckQuyen("DM_ChucVu", "Sua"))
            {
                return Json("Không Có Quyền Truy Cập", JsonRequestBehavior.AllowGet);
            }

            if (ModelState.IsValid)
            {
                db.Entry(dM_ChucVu_ChucDanh).State = EntityState.Modified;
                db.SaveChanges();
                return Json(true, JsonRequestBehavior.AllowGet);
            }
            return Json(false, JsonRequestBehavior.AllowGet);
        }

        public JsonResult GetSuaChucVu(int id)
        {
            var data = (from cv in db.DM_ChucVu_ChucDanh
                        where cv.Ma_ChucVu_ChucDanh == id
                        select new { cv.Ma_ChucVu_ChucDanh, cv.Ten_ChucVu_ChucDanh }).Single();
            return Json(data, JsonRequestBehavior.AllowGet);
        }

        
        [HttpPost, ActionName("Delete")]
        public JsonResult DeleteConfirmed(int id)
        {

            if (user.CheckQuyen("DM_ChucVu", "Xoa"))
            {
                return Json("Không Có Quyền Truy Cập", JsonRequestBehavior.AllowGet);
            }

            DM_ChucVu_ChucDanh dM_ChucVu_ChucDanh = db.DM_ChucVu_ChucDanh.Find(id);
            var data = new
            {
                id = dM_ChucVu_ChucDanh.Ma_ChucVu_ChucDanh,
                Ten = dM_ChucVu_ChucDanh.Ten_ChucVu_ChucDanh
            };
            db.DM_ChucVu_ChucDanh.Remove(dM_ChucVu_ChucDanh);
            db.SaveChanges();

            return Json(data, JsonRequestBehavior.AllowGet);
        }

    }
}

KeKhaiTaiSanThuNhap/Views/DM_ChucVu_ChucDanh/Index.cshtml
@{
    ViewBag.Title = "Danh Mục Chức Vụ - Chức Danh";
    Layout = "~/Views/Shared/_Layout.cshtml"; 
}

<section class="content-header">
    <div class="container-fluid">
        <div class="row mb-2">
            <div class="col-sm-6">
                <ol class="breadcrumb float-sm-left">
                    <li class="breadcrumb-item"><a href="@Url.Action("Index","Home")">Trang chủ</a></li>
                    <li class="breadcrumb-item active">Danh Mục Chức Vụ - Chức Danh</li>
                </ol>
            </div>
        </div>
    </div>
</section>

<section class="content">
    <div class="container-fluid">
        <div class="row">
            <div class="col-12">
                <div class="card elevation-2">
                    <div class="card-tools">
                        <div class="input-group input-group-sm row">


                            <input type="text" name="table_search" class="form-control float-right mr-1" placeholder="Tìm..." id="Filter">
                            <div class="input-group-append mr-3">
                                <button type="submit" class="btn btn-default" id="search_btn">
                                    <i class="fas fa-search text-primary"></i>
                                </button>
                            </div>
                            <div class="input-group-append">
                                <button type="button" class="btn btn-primary" data-toggle="modal" data-target="#add-sh" id="THEM">
                                    <i class="fas fa-plus pr-2"></i>Thêm Mới
                                </button>
                            </div>
                        </div>
                    </div>

                    <table class="table table-hover text-nowrap table-bordered" id="dataTable" style="width: 100%">
                        <thead class="bg-primary">
                            <tr>
                                <th width="5%">STT</th>
                                <th width="90%">Tên Chức Vụ - Chức Danh</th>
                                <th width="5%"></th>
                            </tr>
                        </thead>
                        <tbody>
                        </tbody>
                    </table>
                    <div class="card-footer clearfix" style="height: 51px; width: 100%">
                        <ul class="pagination pagination-sm m-0 float-right">
                        </ul>
                    </div>

                </div>
            </div>
        </div>
        <div class="modal fade" id="add-sh">
            <div class="modal-dialog modal-lg">
                <div class="modal-content">
                    <div class="modal-header">
                        <h4 class="modal-title">Thêm Danh Mục Chức Vụ - Chức Danh</h4>
                        <button type="button" class="close closeform" data-dismiss="modal" aria-label="Close">
                            <span aria-hidden="true">×</span>
                        </button>
                    </div>
                    <div class="modal-body">
                        @using (Ajax.BeginForm("Create", "DM_ChucVu_ChucDanh", new AjaxOptions { HttpMethod = "POST", OnSuccess = "FnSuccess", OnFailure = "Failure", OnBegin = "FnBegin" }, new { @class = "DM_Create form-horizontal", @id = "formChucDanh" }))
                        {
                            @Html.AntiForgeryToken()
                            <div class="card-body">
                                <div class="form-group row">
                                    <label for="cnsh" class="col-sm-3 col-form-label">Tên Chức vụ Chức Danh <span style="color: red"> *</span></label>
                                    <div class="col-sm-9">
                                        <input type="text" class="form-control" placeholder="nhập tên chức vụ" id="Ten_ChucVu_ChucDanh" name="Ten_ChucVu_ChucDanh" required>
                                    </div>
                                </div>

                            </div>
                            <div class="modal-footer justify-content-between">
                                <button type="button" class="btn btn-danger closeform" data-dismiss="modal" style="width: 105px">
                                    Đóng
                                </button>
                                <button type="submit" class="btn btn-primary" style="position: relative; width: 105px;">
                                    <svg xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" style="background: none; display: block; shape-rendering: auto; margin: 0px; padding: 0px; width: 20px; height: 20px; position: absolute;left: 5px;top: 6px;" viewBox="0 0 100 100" preserveAspectRatio="xMidYMid" class="loading_newchucvu d-none">
                                        <circle cx="50" cy="50" r="32" stroke-width="8" stroke="#ffffff" stroke-dasharray="50.26548245743669 50.26548245743669" fill="none" stroke-linecap="round">
                                            <animateTransform attributeName="transform" type="rotate" repeatCount="indefinite" dur="1s" keyTimes="0;1" values="0 50 50;360 50 50"></animateTransform>
                                        </circle>
                                    </svg>
                                    Lưu Mới
                                </button>
                            </div>
                        }
                    </div>
                </div>
            </div>
        </div>
        <div class="modal fade" id="add-sh1">
            <div class="modal-dialog modal-lg">
                <div class="modal-content">
                    <div class="modal-header">
                        <h4 class="modal-title">Cập Nhật Danh Mục Chức Vụ - Chức Danh</h4>
                        <button type="button" class="close closeform" data-dismiss="modal" aria-label="Close">
                            <span aria-hidden="true">×</span>
                        </button>
                    </div>
                    <div class="modal-body">
                        @using (Ajax.BeginForm("Edit", "DM_ChucVu_ChucDanh", new AjaxOptions { HttpMethod = "POST", OnSuccess = "FnSuccess_Edit", OnFailure = "Failure_Edit", OnBegin = "FnBegin_Edit" }, new { @class = "DM_Edt form-horizontal" }))
                        {
                            @Html.AntiForgeryToken()
                            <div class="card-body">
                                <div class="form-group row">
                                    <label for="cnsh" class="col-sm-3 col-form-label">Tên Chức Vụ Chức Danh <span style="color: red"> *</span></label>
                                    <div class="col-sm-9">
                                        <input type="hidden" disable="true" class="form-control" id="Ma_ChucVu_ChucDanh_edt" name="Ma_ChucVu_ChucDanh" value="">
                                        <input type="text" class="form-control" placeholder="nhập tên chức vụ" id="Ten_ChucVu_ChucDanh_edt" name="Ten_ChucVu_ChucDanh" value="">
                                    </div>
                                </div>
                                <div class="modal-footer justify-content-between">
                                    <button type="button" class="btn btn-danger closeform" data-dismiss="modal" style="width: 110px">
                                        Đóng
                                    </button>
                                    <button type="submit" class="btn btn-primary" style="position: relative; width: 110px;">
                                        <svg xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" style="background: none; display: block; shape-rendering: auto; margin: 0px; padding: 0px; width: 20px; height: 20px; position: absolute;left: 5px;top: 6px;" viewBox="0 0 100 100" preserveAspectRatio="xMidYMid" class="loading_editxaphuong d-none">
                                            <circle cx="50" cy="50" r="32" stroke-width="8" stroke="#ffffff" stroke-dasharray="50.26548245743669 50.26548245743669" fill="none" stroke-linecap="round">
                                                <animateTransform attributeName="transform" type="rotate" repeatCount="indefinite" dur="1s" keyTimes="0;1" values="0 50 50;360 50 50"></animateTransform>
                                            </circle>
                                        </svg>
                                        Cập nhật
                                    </button>
                                </div>

                            </div>
                        }
                    </div>
                </div>
            </div>
        </div>

    </div>
</section>

<script src="~/Scripts/DanhMuc/DM_ChucVu_ChucDanh.js"></script>